//
// Created by Martin on 23.11.2023.
//

#ifndef PROJECT_LUMINARY_INTERACTIVEOBJECT_H
#define PROJECT_LUMINARY_INTERACTIVEOBJECT_H


class InteractiveObject {

};


#endif //PROJECT_LUMINARY_INTERACTIVEOBJECT_H
