#ifndef PROJECT_LUMINARY_CONSOLEFORMATTYPE_H
#define PROJECT_LUMINARY_CONSOLEFORMATTYPE_H

enum ConsoleFormatType {
    RESET = 0,
    ITALIC = 3,
    UNDERLINE = 4,
    BLINKING = 5,
    INVERTED = 7,
    STRIKETHROUGH = 9
};

#endif //PROJECT_LUMINARY_CONSOLEFORMATTYPE_H
