#ifndef PROJECT_LUMINARY_CONSOLEFORMATTYPE_H
#define PROJECT_LUMINARY_CONSOLEFORMATTYPE_H

enum ConsoleFormatType {
    RESET, ITALIC, BLINKING, INVERTED, UNDERLINE, STRIKETHROUGH
};

#endif //PROJECT_LUMINARY_CONSOLEFORMATTYPE_H
